name: Flutter Deploy
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: '${{ needs.build.outputs.artifact_name }}'
          path: build/web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELOIT_C4540 }}'
          channelId: live
          projectId: eloit-c4540
