name: Flutter Test and Build
on: 
  workflow_call:
    outputs:
      artifact_name:
        description: "flutter build web output artifact name"
        value: ${{ jobs.test_and_build_web.outputs.name }}

  workflow_dispatch:
  push:


jobs:
  test_and_build_web:
    runs-on: ubuntu-latest

    outputs:
      name: 'build-web-${{ github.action }}-${{github.run_number}}'

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Get all Flutter Packages
        run: flutter pub get
      - name: Run Flutter Test
        run: flutter test
      - name: Build Web Folder
        run: flutter build web
      - name: upload web build
        uses: actions/upload-artifact@v3
        with:
          name: 'build-web-${{ github.action }}-${{github.run_number}}'
          path: build/web
          retention-days: 5
      - name: deploy to preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ELOIT_C4540 }}'
          projectId: eloit-c4540
          expires: 3d
          channelId: '${{ github.ref_name }}'
