name: Flutter Test and Build
on: 
  workflow_call:
    outputs:
      artifact_name:
        description: "flutter build web output artifact name"
        value: ${{ jobs.test_and_build_web.outputs.name }}

  workflow_dispatch:
  push:


jobs:
  test_and_build_web:
    runs-on: ubuntu-latest

    outputs:
      name: build-web-${{ github.ref }}-${github.run_number}

    steps:
      - uses: actions/checkout@v3
      - name: Get all Flutter Packages
        run: flutter pub get
      - name: Run Flutter Test
        run: flutter test
      - name: Build Web Folder
        run: flutter build web
      - name: upload web build
        uses: actions/upload-artifact@v3
        with:
          name: build-web-latest
          path: build/web
          retention-days: 5
